### PR TITLE
Added Name and Fixed Alignment

### PR DESCRIPTION
**Pull request by indranil-tiwary**
Added my name and fixed alignment at contributors.html file.

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
To be on the contribution list you actually have to contribute with something 🙂
Closing this but you can make a new pull request when you contributed.

**Comment by indranil-tiwary** [comment]
@BennyCarlsson I contributed in helpful-material link. Can you please re-open?

**Comment by BennyCarlsson** [comment]
oh I missed that sorry :) merging this ;)

**Comment by indranil-tiwary** [comment]
Thank you @BennyCarlsson

**Pull request merged**
