### PR TITLE
#762 fixed Navbar links and some other issues.

### PR DESCRIPTION
**Pull request by CQW-Code**

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
Some fixes here is probably not valid anymore since we updated the navbar. We happily merge the other changes if you update the pull request or make a new one :)

**Comment by CQW-Code** [comment]
what?  I thought I fixed all the conflicts?  And it sounds like probably my hard work on the contributors page is moot anyway...?  :(  So I don't even know if it's worth fixing it all as it's all been done no?

**Comment by CQW-Code** [comment]
I'm closing this.  Apparently someone else decided to make the contributor page look nice (the only thing that looks awful is that some of the cards with longer names throws off the neatness of the columns (that's one thing I did- just widened the width of the card-item).  So my contribution was pretty much wiped (and my ducky easter egg is gone as well).  Thank you for the chance to try though- I was super proud I was able to figure out the menu issue on the contributor page (drop down wouldn't open lol) before the massive overhaul done in the meantime and the design I did - I liked the black background lol.

**Comment by BennyCarlsson** [comment]
@CQW-Code Sorry your pull requests didn't get merged :/ we get a lot of pull requests and we try to merge as many ass possible from everyone. Still good work and you should be proud ;)

Feel free to do new pull requests maybe one with just the easter egg? :)

**Comment by CQW-Code** [comment]
I forgot the easter egg when I did the tools page! lol.. I'll add back soon.

**Pull request closed without merging**
