### PR TITLE
Fixed footer issue in contributors page

### PR DESCRIPTION
**Pull request by SarathSantoshDamaraju**

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
Seems to be a merge conflict, probably because we merge a lot of pull requests :) I'll happily
merge this one aswell if you have time fixing it :)

**Comment by SarathSantoshDamaraju** [comment]
Sure

**Comment by SarathSantoshDamaraju** [comment]
@BennyCarlsson , Done !!

**Comment by BennyCarlsson** [comment]
yeah sorry about that we try to merge a lot of pull requests all the time :)

**Pull request merged**
