### PR TITLE
added highlight to active nav item

### PR DESCRIPTION
**Pull request by simpslandyy**
Please review @richie-south 
For issue #1299

### CODE REVIEW

**Comment by richie-south** [comment]
I can see that you added active css styles but is it in use anywhere?

**Comment by simpslandyy** [comment]
@richie-south yeah, whenever the nav bar item is active. When I checked index.html on my branch it appears.

**Comment by richie-south** [comment]
@simpslandyy Okay :) I don't see it on the live page however, have you forgotten to commit something? :)

**Comment by simpslandyy** [comment]
image
@richie-south I tried changing the color from pink to green on my branch, and I still see it.
The problem seems to be in menu.js.
This check will always return false on production:
```       let isCurrent = (currentPage === item.href) ```
Because currentPage doesn't have the file path ".html" when deployed on production, whereas on our local branches it definitely will.

**Comment by richie-south** [comment]
@simpslandyy Aa i understand :) could we remove the `.html` from `item.href` with something like this ( `item.href.replace('.html', '')` ) only during comparison? :)

**Comment by simpslandyy** [comment]
@richie-south we could, but then it would break for the people testing locally, because currentPage would still have the file type ".html".
I'm thinking to just do a check to see if ".html" is included in currentPage & if not, add it for the comparison. 
```
  if (currentPage.indexOf('.html') == -1) {
        currentPage = currentPage.concat('.html')
}
```

**Comment by richie-south** [comment]
@simpslandyy Yea that could work :) Submit a pull request and i will merge it 😉

**Pull request merged**
