### PR TITLE
 Small little Broccoli Easter Egg <3

### PR DESCRIPTION
**Pull request by Broccolai**

### CODE REVIEW

**Comment by Broccolai** [comment]
not sure why its included all those commits my bad, only knew one is the one called "Small little Broccoli Easter Egg <3"

**Comment by BennyCarlsson** [comment]
Can't find the button but merging it and will continue to look for it :)

**Comment by BennyCarlsson** [comment]
aahh I found it haha xD

**Comment by Broccolai** [comment]
;)

**Pull request merged**
