### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by srprescott**

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
Hi did you have some kind of auto beautify? It will cause some bad merge conflict if you use that :/ also not sure what changes you made? :)

**Comment by srprescott** [comment]
Hello! I don't use Beautify. I messed up when merging the files, sorry for the mistake, I'm new to Github and still working out how this all works. Please let me know what I can do to fix these conflicts. Thank you!

**Comment by BennyCarlsson** [comment]
@srprescott No problem Github is tricky and I mess up things sometimes to ;) I'm not sure what **Add files via upload** is for feature but if you can't solve the merge conflict (we have a video on the website on how to do that) it might be easier to close this one and make a new pull request ;)

**Comment by srprescott** [comment]
That's a good idea, I'll try again! Also, your portfolio site looks great!

**Comment by BennyCarlsson** [comment]
@srprescott Great looking forward to your pull request :) and thanks :)

**Pull request closed without merging**
