### PR TITLE
add image processing with java project

### PR DESCRIPTION
**Pull request by NSLog0**
1. Add project for learning basic image processing which is implemented with java 
2. Fix HTML style

This addresses issue https://github.com/lingonsaft/hacktoberfest/issues/6

### CODE REVIEW

**Comment by ksandhu16** [comment]
How can I resolve this issue?

**Comment by NSLog0** [comment]
@ksandhu16 Solve Conflicting, Right?

**Comment by ksandhu16** [comment]
Sorry can you elaborate?

**Comment by ksandhu16** [comment]
Can I do a pull request and share a good opensource project that I like ?

**Comment by NSLog0** [comment]
Yes, I did that.

This PR it's my project which created, since university

**Pull request closed without merging**
