### PR TITLE
Hacktoberfest checker

### PR DESCRIPTION
**Pull request by Poeschl**
I was missing a link to the [Hacktoberfest checker](https://hacktoberfestchecker.herokuapp.com/). 
It is a useful tool to track your personal progress and link to it might help others.

Added the link on:
- the navigation bars
- the index page

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
Seems to be a merge conflict, probably because we merge a lot of pull requests :) I'll happily
merge this one aswell if you have time fixing it :)

**Comment by Poeschl** [comment]
Rebased ;)

**Comment by BennyCarlsson** [comment]
Great :)

**Comment by Poeschl** [comment]
Happy to help

**Pull request merged**
