### PR TITLE
Fix helpful material page layout

### PR DESCRIPTION
**Pull request by heyztb**
The page has some misapplied classes in the live version of the website. This pull request fixes that.

Before: http://prntscr.com/l2ss61
The four items in boxes are actually apart of the "Beginner friendly projects list", but due to having some classes unnecessarily applied they appear in a different section. Furthmore, they repeat later down the page for some reason.

After: http://prntscr.com/l2ssqs

And there were some list items that had been placed outside of a div further down the page, which caused them to be out of alignment with the rest of the list. This has also been fixed.

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
That is great good job :) however there seems to be a merge conflict because we merged something earlier. Do you have time to fix it?

**Comment by heyztb** [comment]
@BennyCarlsson - Yes, I'll take a look at the merge conflict and see what I can do to resolve it.

**Comment by heyztb** [comment]
Hmm. I apparently didn't look close enough. There are still some misapplied classes in this commit.

**Comment by BennyCarlsson** [comment]
Great thanks :)

**Pull request merged**
