### PR TITLE
Formatted all 3 html files to follow rough guidelines added to README doc. Added myself to contributors.

### PR DESCRIPTION
**Pull request by nmcateer**
Formatted all 3 html files to follow rough guidelines added to README doc. Added myself to contributors.

### CODE REVIEW

**Comment by richie-south** [comment]
This is great! If you could fix the conflicts with in a couple of minutes (10 - 20) i will not merge anything before you are done 👍 👍

**Comment by nmcateer** [comment]
Nearly there - the helpful-material page has just took abit more work to ensure they right ones are merged together

**Comment by nmcateer** [comment]
merge conflicts sorted

**Comment by richie-south** [comment]
Yeay will merge!

**Comment by nmcateer** [comment]
sweet super!

**Pull request merged**
