### PR TITLE
Updated the styling

### PR DESCRIPTION
**Pull request by Kvaibhav01**
Also, added a button for the repo's webpage.

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
Hi looks like we got a merge conflict because we merged earlier pull requests. Have time to fix it?

**Comment by Kvaibhav01** [comment]
I would love to, but I don't know what to change or how to resolve it.

**Comment by richie-south** [comment]
Hey @Kvaibhav01 This video might help https://www.youtube.com/watch?v=zOx5PJTY8CI&feature=youtu.be If not let me know 😃

**Comment by Kvaibhav01** [comment]
Done @richie-south! Thank you for the video 😀

**Pull request closed without merging**
