### PR TITLE
Fix Helpful-Material

### PR DESCRIPTION
**Pull request by sn149**
fixed

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
hmm you seemed to have some merge stuff left in the code ;) check our video about merge conflict on the website :)

**Comment by sn149** [comment]
fixed

**Comment by BennyCarlsson** [comment]
hmm still seems like you have a lot of ==== in the code

**Comment by sn149** [comment]
resolved all conflict :grin:

**Comment by BennyCarlsson** [comment]
Great work :) merging it now

**Pull request merged**
