### PR TITLE
added keywords meta tag to html head

### PR DESCRIPTION
**Pull request by terryjreynolds**
Keywords to increase SEO.

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
Great but did you use some kind of auto beautify? or auto indentation? because this makes it really hard with merge conflicts :)

**Comment by terryjreynolds** [comment]
Oh oh. Sorry. Novice error. I’m using Prettier in VS Code. How can I remedy this?

**Comment by terryjreynolds** [comment]
I’m guessing I’ll have to delete this PR, fork again and turn off the editor extension and then submit a new PR?

**Comment by BennyCarlsson** [comment]
that would probably be the easiest way :)

**Pull request closed without merging**
