### PR TITLE
Added consistent header-menu and footer (issue #78)

### PR DESCRIPTION
**Pull request by CCAtAlvis**

### CODE REVIEW

**Comment by richie-south** [comment]
Great!!!!! If you solve the conflicts i will merge this right away! 😃

**Comment by CCAtAlvis** [comment]
cool! i will look into them!

**Comment by richie-south** [comment]
Looks like this also fixes #85 😃

**Comment by CCAtAlvis** [comment]
Ohh #85 .. thats was opened after i started to look into this.. simply added some margin-bottom 😆 
also merged the branches!

**Comment by richie-south** [comment]
Now it's perfect <3

**Pull request merged**
