### PR TITLE
Fix #286

### LINKED ISSUE #286: Footer is to big at the moment
Change design on footer is to big and wrong color at the moment :)

### PR DESCRIPTION
**Pull request by CruiseDevice**

### CODE REVIEW

**Comment by richie-south** [comment]
Awesome :D :D Great work

**Comment by CruiseDevice** [comment]
Thanks :)

**Comment by CruiseDevice** [comment]
I actually forgot to add myself to contributors.

**Comment by BennyCarlsson** [comment]
No problem just make a new pull request ;)

**Pull request merged**
