### PR TITLE
Fixed styling on Contributor + Helpful Material Page

### PR DESCRIPTION
**Pull request by ktan114**

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
Seems to be a merge conflict, probably because we merge a lot of pull requests :) I'll happily
merge this one aswell if you have time fixing it :)

**Comment by ktan114** [comment]
Resolved!

**Comment by ktan114** [comment]
Looks like constant merges keep causing conflicts especially in the contributor file

**Comment by richie-south** [comment]
Merging this now :)

**Pull request merged**
