### PR TITLE
Update style Contributors

### PR DESCRIPTION
**Pull request by sn149**
Update Contributors

### CODE REVIEW

**Comment by richie-south** [comment]
Hey looks great! But could you resolve the conflicts? 👍 👍

**Comment by sn149** [comment]
done :grin:

**Comment by richie-south** [comment]
Great but did you readd the old navbar? :)

**Comment by sn149** [comment]
@richie-south navbar fixed :smile:

**Comment by BennyCarlsson** [comment]
Great :)

**Pull request merged**
