### PR TITLE
Added easter egg: hearts appear above and below header

### PR DESCRIPTION
**Pull request by Casva**
Hey there!
I've added an Easter Egg to make more hearts appear (#484 #486)
Just click on here to add hearts above and below the main header.

image

A tool tip has been added as well :)
Hope it's not too late since the issue was closed!

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
Hi @Casva I Like your easter egg ❤️ I will happily merge it if you have time to fix the merge conflict :) also don't worry if the ticket is closed people can still add easter eggs ;)

**Comment by Casva** [comment]
Should be good now!

**Comment by Casva** [comment]
Hey @BennyCarlsson ! 
Bumping this back up. There were a lot changes that kept happening to the files so I just did a rebase instead. Hope this can still get merged in! :)

**Comment by BennyCarlsson** [comment]
Oh missed that you updated this :) Great work it's merged now

**Pull request merged**
