### PR TITLE
Added container class and aligned it to center

### PR DESCRIPTION
**Pull request by sarveshggn**

### CODE REVIEW

**Comment by richie-south** [comment]
It should have bean like this from the start! Thanks 😃

**Comment by pvn6396** [comment]
> It should have bean like this from the start! Thanks

The social links are not visible after this merge.

**Comment by richie-south** [comment]
@pvn6396 Oops i must have missed that in my review 😢 Would you mind creating an issue about this?

**Comment by pvn6396** [comment]
Oops!!! that is a toggle social link button.

**Comment by richie-south** [comment]
Haha, maybe we should make it clearer?  cursor: pointer; maybe?

**Pull request merged**
