### PR TITLE
Added fork syncing into readme.md

### PR DESCRIPTION
**Pull request by cnettelblad**
Essentially just a TLDR from Githubs own article about it.

### CODE REVIEW

**Comment by richie-south** [comment]
Hey great 👍

**Comment by richie-south** [comment]
But it looks like the nav bar is removed? Cannot se inte in index.html 
https://lingonsaft-hacktober-dhrfygphzu.now.sh/

**Comment by cnettelblad** [comment]
> But it looks like the nav bar is removed? Cannot se inte in index.html
> https://lingonsaft-hacktober-dhrfygphzu.now.sh/

Seemed to be a conflict, fixed it and it seems to work now.

**Comment by BennyCarlsson** [comment]
Great good job :)

**Pull request merged**
