### PR TITLE
Changes to color of Start Hacking button

### PR DESCRIPTION
**Pull request by saideepd**
Changed color of Start Hacking button to match with fire emoticon and changed color of text to be compatible with button color

### CODE REVIEW

**Comment by richie-south** [comment]
Ooo thats cool! Can we fix the conflicts so i can merge? 🥇

**Comment by saideepd** [comment]
Hey @richie-south would love to get my PR merged. Fixed the conflicts causing issues 😉👍

**Comment by saideepd** [comment]
Hey @richie-south when I solved the conflicting issues the now bot didn't show any conflicts and was all OK. But now its showing conflicts because I have made changes in index.html which don't match with master branch. The color of button can't be changed if I don't remove the type="button". Or else I have to make changes in CSS files which too caused conflicts in earlier commit. Please check in this.

**Comment by richie-south** [comment]
Hey thats okey 👍 It looks great i finally merged your pull request <3

**Comment by saideepd** [comment]
Thanks for the merge @richie-south . Don't know why the bot caused such issue. Happy to contribute to Open Source projects ❤

**Pull request merged**
