### PR TITLE
remove cashmoney.html

### PR DESCRIPTION
**Pull request by pydevsg**
Removing unnecessary file cashmoney.html
Issue #2030 Delete pages!

### CODE REVIEW

**Comment by richie-south** [comment]
Nice work once again!

**Comment by pydevsg** [comment]
Thanks richie-south again.

**Comment by pydevsg** [comment]
Sir,can I write my name in contribution page now,if you allow me so?

**Comment by richie-south** [comment]
@pydevsg Yes of course!!!! <3

**Pull request merged**
