### PR TITLE
Using one united json menu

### PR DESCRIPTION
**Pull request by cnettelblad**
Now people can easily change the menu and it will be effective on all pages.

Will probably add a few more features to this later on.

### CODE REVIEW

**Comment by cnettelblad** [comment]
I'll try to fix the conflicts right away, bare with me.

**Comment by richie-south** [comment]
Ooo nooooo 😢 I'm sorry we missed this :( (So many pull requests)
But if you have time to fix the conflicts one last time we promise to merge this ❤️

**Comment by cnettelblad** [comment]
> Ooo nooooo 😢 I'm sorry we missed this :( (So many pull requests)
> But if you have time to fix the conflicts one last time we promise to merge this ❤️

I've resolved it now, does however remove the dropdown so someone else or me will have to add it to the script in order for it to work - will make for some nice json structure though so I'll try to get it in a new PR if this one gets merged.

**Comment by cnettelblad** [comment]
This PR may or may not be very dependent on this one: https://github.com/lingonsaft/hacktoberfest/pull/824

**Comment by BennyCarlsson** [comment]
Awesome! This was really needed. Thanks for updating the merge conflict aswell :)

**Pull request merged**
