### PR TITLE
styled the content above contribution rules with bootstap 4

### PR DESCRIPTION
**Pull request by kokochef**
the content above the contribution rules part is beautifully responsive. Thanks to bootstrap 4.

### CODE REVIEW

**Comment by richie-south** [comment]
Hey you should fix the conflicts otherwise great work 👍

**Comment by kokochef** [comment]
Good to know you liked it. I'm new to fixing conflicts so I'll get it done asap.

**Comment by richie-south** [comment]
@kokochef It's okey take your time 😃 And if you get stuck we created this guide hope it helps https://www.youtube.com/watch?v=zOx5PJTY8CI

**Comment by richie-south** [comment]
@kokochef yes it works! Will merge

**Pull request merged**
