### PR TITLE
Closes #1021 font-awesome issue

### LINKED ISSUE #1021: font-awesome not loading
Font awesome css file is loaded but font-awesome is not showing on footer icons(social media accounts)

wrong css class assigned

### PR DESCRIPTION
**Pull request by sadikkuzu**
This closes #1021 font-awesome issue

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
this breaks the icons in the footer of index.html :P

**Comment by pawansingh972** [comment]
@sadikkuzu @BennyCarlsson yeah because it downgrades the FontAwesome Version

**Comment by sadikkuzu** [comment]
and now? @BennyCarlsson

**Comment by pawansingh972** [comment]
> and now? @BennyCarlsson

Now It should be fine.

**Comment by BennyCarlsson** [comment]
Yes! Great work :)

**Pull request merged**
