### PR TITLE
Sort all lists on "Helpful Material" page

### PR DESCRIPTION
**Pull request by mukul-kgp**

### CODE REVIEW

**Comment by richie-south** [comment]
Looks great, if you have time to solve the conflicts i will merge this! 😃

**Comment by richie-south** [comment]
Looks like i merged something that gave you another conflict i'm sorry 😞

**Comment by mukul-kgp** [comment]
Peace!
Since i'm new, could you suggest what I should do next?

**Comment by richie-south** [comment]
You could checkout this or any other video on merge conflicts 😃 https://www.youtube.com/watch?v=zOx5PJTY8CI&feature=youtu.be If you need more help just let me know!

**Pull request closed without merging**
